apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: development
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: kholha/exp-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-configs
                  key: public_api_url
            - name:  NEXT_APP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: app-api-key
