---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-class
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: gp3
